<a href="https://colab.research.google.com/github/abdelwahedmodest/Abdelwahed/blob/master/breast_cancer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
addresse ='https://raw.githubusercontent.com/jbrownlee/Datasets/master/breast-cancer.csv'

In [7]:
import pandas as pd
# load the dataset
dataset = pd.read_csv(addresse, header=None)
# retrieve the array of data
data=dataset.values

In [9]:
dataset.head()

0          1        2  ...           7      8                       9
0  '40-49'  'premeno'  '15-19'  ...   'left_up'   'no'     'recurrence-events'
1  '50-59'     'ge40'  '15-19'  ...   'central'   'no'  'no-recurrence-events'
2  '50-59'     'ge40'  '35-39'  ...  'left_low'   'no'     'recurrence-events'
3  '40-49'  'premeno'  '35-39'  ...  'left_low'  'yes'  'no-recurrence-events'
4  '40-49'  'premeno'  '30-34'  ...  'right_up'   'no'     'recurrence-events'

[5 rows x 10 columns]

In [11]:
# separate into input and output columns
X = data[:, :-1].astype(str)
y = data[:, -1].astype(str)

In [14]:
# summarize
print('Input', X.shape)
print('Output', y.shape)

Input (286, 9)
Output (286,)


In [16]:
from sklearn.preprocessing import OrdinalEncoder
# ordinal encode input variables
ordinal = OrdinalEncoder()
X = ordinal.fit_transform(X)

In [18]:

from sklearn.preprocessing import LabelEncoder
# ordinal encode target variable
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)

In [20]:
# summarize the transformed data
print('Input', X.shape)
print(X[:5, :])
print('Output', y.shape)
print(y[:5])

Input (286, 9)
[[2. 2. 2. 0. 1. 2. 1. 2. 0.]
 [3. 0. 2. 0. 0. 0. 1. 0. 0.]
 [3. 0. 6. 0. 0. 1. 0. 1. 0.]
 [2. 2. 6. 0. 1. 2. 1. 1. 1.]
 [2. 2. 5. 4. 1. 1. 0. 4. 0.]]
Output (286,)
[1 0 1 0 1]


In [21]:
from sklearn.model_selection import  train_test_split

# split the dataset into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=1)

In [22]:
# ordinal encode input variables
ordinal_encoder = OrdinalEncoder()
ordinal_encoder.fit(X_train)
X_train = ordinal_encoder.transform(X_train)
X_test = ordinal_encoder.transform(X_test)

In [23]:
from numpy import mean
from numpy import std
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# ordinal encode target variable
label_encoder = LabelEncoder()
label_encoder.fit(y_train)
y_train = label_encoder.transform(y_train)
y_test = label_encoder.transform(y_test)
# define the model
model = LogisticRegression()
# fit on the training set
model.fit(X_train, y_train)
# predict on test set
yhat = model.predict(X_test)
# evaluate predictions
accuracy = accuracy_score(y_test, yhat)
print('Accuracy: %.2f' % (accuracy*100))

Accuracy: 75.79
